apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: chicago-taxi-demo
  namespace: kubeflow
spec:
  appdir: /home/CIT/rodrigofp/Projects/Specialization2019/demo_taxi/chicago-taxi-forecast/kubeflow_cluster/chicago-taxi-demo
  componentParams:
    ambassador:
    - name: ambassadorServiceType
      value: NodePort
    basic-auth-ingress:
    - initRequired: true
      name: ipName
      value: chicago-taxi-demo-ip
    - initRequired: true
      name: hostname
      value: chicago-taxi-demo.endpoints.ciandt-cognitive-sandbox.cloud.goog
    cert-manager:
    - initRequired: true
      name: acmeEmail
      value: rodrigofp@ciandt.com
    cloud-endpoints:
    - name: secretName
      value: admin-gcp-sa
    notebook-controller:
    - name: injectGcpCredentials
      value: "true"
    pipeline:
    - name: mysqlPd
      value: chicago-taxi-demo-storage-metadata-store
    - name: minioPd
      value: chicago-taxi-demo-storage-artifact-store
    spartakus:
    - initRequired: true
      name: usageId
      value: "2598989099639969828"
    - initRequired: true
      name: reportUsage
      value: "true"
  components:
  - ambassador
  - argo
  - basic-auth
  - basic-auth-ingress
  - centraldashboard
  - cert-manager
  - cloud-endpoints
  - gcp-credentials-admission-webhook
  - gpu-driver
  - jupyter-web-app
  - katib
  - metacontroller
  - notebook-controller
  - pipeline
  - pytorch-operator
  - spartakus
  - tensorboard
  - tf-job-operator
  email: rodrigofp@ciandt.com
  hostname: chicago-taxi-demo.endpoints.ciandt-cognitive-sandbox.cloud.goog
  ipName: chicago-taxi-demo-ip
  packages:
  - argo
  - common
  - examples
  - gcp
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pipeline
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  platform: gcp
  project: ciandt-cognitive-sandbox
  repo: /home/CIT/rodrigofp/Projects/Specialization2019/demo_taxi/chicago-taxi-forecast/kubeflow_cluster/chicago-taxi-demo/.cache/v0.5.1/kubeflow
  serverVersion: file:/home/CIT/rodrigofp/Projects/Specialization2019/demo_taxi/chicago-taxi-forecast/kubeflow_cluster/chicago-taxi-demo/.cache/v0.5.1/bootstrap/k8sSpec/v1.11.7/api/openapi-spec/swagger.json
  useBasicAuth: true
  useIstio: false
  version: v0.5.1
  zone: us-east1-d
status: {}
